### ISSUE TITLE
Uncorrect result when converting from ACES_CG to ENCODED_BT_709

### ISSUE THREAD

**Issue by oumad** [BoxDragon/kolor#12]
I'm trying to convert an EXR done in ACES_CG color space to png with encoded BT_709.

The result I'm expecting to get : 
![toy_car](https://user-images.githubusercontent.com/17836943/202875675-c50883b6-1f3f-494b-b226-4893b24ce412.png)

The actual result I'm getting using my code : 
![toy_car_BT_709](https://user-images.githubusercontent.com/17836943/202875679-73a8261c-dbd6-49d6-9138-7822f3c34e16.png)

As you can see we lose a lot of nuances in the colors and highlights.

This is the source EXR file : 
[toy_car.zip](https://github.com/BoxDragon/kolor/files/10048122/toy_car.zip)

And this is the code I'm using for the conversion : 
```rust
extern crate image as png;
// exr imports
extern crate exr;
extern crate kolor;

/// Converts one rgba exr with one layer to one png, or fail.
pub fn exr_convert() {
    use exr::prelude::*;
    use exr::prelude as exrs;

    let conversion = kolor::ColorConversion::new(
      kolor::spaces::ACES_CG,
      kolor::spaces::ENCODED_BT_709,
    );

    // read from the exr file directly into a new `png::RgbaImage` image without intermediate buffers
    let reader = exrs::read()
        .no_deep_data()
        .largest_resolution_level()
        .rgba_channels(
        |resolution, _channels: &RgbaChannels| -> png::RgbaImage {
                png::ImageBuffer::new(
                    resolution.width() as u32,
                    resolution.height() as u32
                )
            },
            // set each pixel in the png buffer from the exr file
            move |png_pixels, position, (r,g,b,a): (f32,f32,f32,f32)| { 
                let linear_color = kolor::Vec3::new(r,g,b);
                let srgb_color = conversion.convert(linear_color);
                png_pixels.put_pixel(
                    position.x() as u32, position.y() as u32,
                    png::Rgba([(srgb_color[0]* 255.0) as u8, (srgb_color[1]* 255.0) as u8, (srgb_color[2]* 255.0) as u8, (a * 255.0) as u8])
                );
            }
        )
        .first_valid_layer()
        .all_attributes();

    // an image that contains a single layer containing a png rgba buffer
    let image: Image<Layer<SpecificChannels<png::RgbaImage, RgbaChannels>>> = reader
        .from_file("F:/dev/testing/source/exr/toy_car.exr")
        .expect("run the `1_write_rgba` example to generate the required file");

    // save the png buffer to a png file
    let png_buffer = &image.layer_data.channel_data.pixels;
    png_buffer.save("F:/dev/testing/source/exr/toy_car_BT_709.png").unwrap();
    println!("created rgb png image")
}

```

**Comment by oumad** [comment]
I finally got a more correct result, but this time I'm using [colstodian ](https://docs.rs/colstodian/0.1.0-rc.3/colstodian/) crate which is built on top of `kolor`.

This is the result : 
![toy_car_aces_cg_to_srgb](https://user-images.githubusercontent.com/17836943/202932778-7ff26f48-bed6-4e0b-a493-fa066faa9261.png)

This is the source target for comparison : 
![toy_car_SOURCE_SRGB](https://user-images.githubusercontent.com/17836943/202932785-978c19c6-cf7c-48df-ada1-0bb019f27a15.png)

The conversion version is a bit lighter than the target, maybe it's some parameter in tonemaping, but at least the colors behave more correctly, almost there !

The conversion code : 
```rust
fn aces_cg_to_srgb(r:f32,g:f32,b:f32,a:f32) -> [u8; 3] {
  let rendered_col = color::acescg(r, g, b);
  let params = PerceptualTonemapperParams::default();
  let tonemapped: Color<AcesCg,Display> = PerceptualTonemapper::tonemap(rendered_col, params).convert();
  let encoded = tonemapped.convert::<EncodedSrgb>();
  return encoded.to_u8();
}
```

**Comment by kabergstrom** [comment]
Glad to hear you got the result you wanted. Let me know if there are any other issues :)
